### ISSUE TITLE
Some labels are inaccurate from pokecrystal

### ISSUE THREAD

**Issue by Rangi42** [pret/pokegold#28]
e.g. `BurnedTowerB1FEusineText` in maps/BurnedTowerB1F.asm is some unused Entei text.

**Comment by entrpntr** [comment]
BurnedTower1F has some label issues as well: Eusine and Morty are given credit for different parts of Firebreather Dick's text. I'd imagine there might be several others in map scripts as well, if the priority was put on matching the scripts and not fixing all the labeling.

Can possibly use this issue to track constants as well, since there is a good amount of leftover pokecrystal stuff there. Eusine is referenced in `constants/event_flags.asm` and `constants/scene_constants.asm`, for instance.

Other ones that immediately come to mind are the use of "Buena" instead of "Beauty" in many places, and the two unused bytes in `box_struct` that became capture data in Crystal. There may be others in current master that I've already addressed in my pull requests; I'll add more if I see anything else I've deliberately skipped over in PRs thus far.

**Comment by Rangi42** [comment]
Some labels are also now *more* accurate than pokecrystal, e.g. `SPRITE_ANIM_INDEX_UNUSED_LAPRAS`, and will need porting back to pokecrystal. @entrpntr if you want, please open an issue to just add such names as you come across them.

**Comment by Rangi42** [comment]
Some references that will need changing:

- Buena (e.g. `SPRITE_BUENA`)
- Eusine (e.g. `SCENE_CIANWOODCITY_SUICUNE_AND_EUSINE`)
- The Wise Trio (e.g. WiseTriosRoom.blk)
- The Ruins of Alph word rooms

**Comment by entrpntr** [comment]
`constants/scene_constants.asm` in general looks like one of the primary offenders remaining as of now; it remained essentially untouched during the recent work, and still contains plenty of references to Crystal-only map scenes.

**Comment by Rangi42** [comment]
Everything mentioned here has been addressed; if more inaccuracies come up, they can just be fixed as they're discovered.
